-- AlterTable
ALTER TABLE "metrics_history" ADD COLUMN     "arm_left" DOUBLE PRECISION,
ADD COLUMN     "arm_right" DOUBLE PRECISION,
ADD COLUMN     "belly" DOUBLE PRECISION,
ADD COLUMN     "buttocks_bottom" DOUBLE PRECISION,
ADD COLUMN     "buttocks_top" DOUBLE PRECISION,
ADD COLUMN     "chest" DOUBLE PRECISION,
ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "leg_left" DOUBLE PRECISION,
ADD COLUMN     "leg_right" DOUBLE PRECISION,
ADD COLUMN     "photos" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "waist" DOUBLE PRECISION;
